name: Daily dataset collection

on:
  schedule:
    # Runs daily at 06:00 UTC = 12:00 Asia/Dhaka (noon)
    - cron: '0 6 * * *'
  workflow_dispatch: {}

jobs:
  collect-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily collector
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
        run: |
          python scripts/collect_daily.py

      - name: Commit and push data changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add data/raw data/master.csv data/districts_geocoded.csv cache/geocode_cache.json || true
          if ! git diff --cached --quiet; then
            git commit -m "Daily dataset update: $(date -u +%Y-%m-%d)"
            git push
          fi

      # Kaggle publishing removed per project scope


